name: jarvis-ci

on:
  push:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    # environment: AWS-EC2-T2-MICRO

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y python3-pyaudio sox libcairo2 libcairo2-dev portaudio19-dev python3-dev libpcre3 libpcre3-dev ffmpeg python3-pip

      - name: CI
        run: ./run_ci.sh
      
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
