name: jarvis-ci

on:
  push:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    environment: Jarvis-CI

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y python3-pyaudio sox libcairo2 libcairo2-dev portaudio19-dev python3-dev libpcre3 libpcre3-dev ffmpeg python3-pip sqlite3 alsa-tools

      - name: CI
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS : ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PICOVOICE_KEY : ${{ secrets.PICOVOICE_KEY }}
          GOOGLE_CLOUD_SECRET : ${{ secrets.GOOGLE_CLOUD_SECRET }}

        run: |
          echo "$GOOGLE_CLOUD_SECRET" > speech-to-text-key.json && ./run_ci.sh && rm -f speech-to-text-key.json
        
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
